# Generated by Django 4.2.3 on 2023-07-31 13:44

from django.db import migrations, models
import image_uploader.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to=image_uploader.models.get_mediafile_upload_to
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("uploader_ip", models.GenericIPAddressField()),
                (
                    "unique_identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "Uploaded Images",
                "ordering": ["-upload_date"],
            },
        ),
    ]
